
// strategy condition type

var STRATEGY_CONDITION_TYPE_CARD_REGION=1;
//var STRATEGY_CONDITION_TYPE_INTERNET=2; internet is changed to company
var STRATEGY_CONDITION_TYPE_COMPANY=2;
var STRATEGY_CONDITION_TYPE_SPACE=3;
var STRATEGY_CONDITION_TYPE_FEATURE_CODE=4;
var STRATEGY_CONDITION_TYPE_CLIENT=5;

var STRATEGY_CONDITION_TYPE_FIRST=1;
var STRATEGY_CONDITION_TYPE_LAST=5;


// audit status
var AUDIT_STATUS_DRAFT = 0;
var AUDIT_STATUS_AUDITING=(1);
var AUDIT_STATUS_AUDIT_PASS=(2);
var AUDIT_STATUS_AUDIT_NO_PASS=(3);
var AUDIT_STATUS_PUBLISH=(4);
var AUDIT_STATUS_UNPUBLISH=(5);


var ENTITY_TYPE_TOPIC=1; // 专题
var ENTITY_TYPE_MENU=2; // 栏目 ?? TopicColumn
var ENTITY_TYPE_ALBUM=3; // 相册
var ENTITY_TYPE_PICTURE=4; // 图片
var ENTITY_TYPE_COLUMN=5; // 版块
var ENTITY_TYPE_ARTICLE=6; // 文章
var ENTITY_TYPE_CARD_REGION=7;
var ENTITY_TYPE_TEMPLATE=8;


var OPERATOR_STATUS_ENABLED=0;
var OPERATOR_STATUS_DISABLED=1;
